### ISSUE TITLE
角色為user的用户在帳戶編輯頁面編輯後按確認出現500 error

### ISSUE THREAD

**Issue by lukechang0815** [isuncloud/isuncrowd#4]
http://test.esangel.com/user/profile/edit
在帳戶編輯頁面編輯後按確認出現500 error

expect
應該出現提示角色為user的用户無法編輯

<h1>PHP Error [8]</h1>
<p>Undefined index: interested (/home/isuntv/文档/CodeC2I/protected/modules/user/worklets/profile/WUserProfileEdit.php:79)</p>
<pre>#0 /home/isuntv/文档/CodeC2I/protected/modules/user/worklets/profile/WUserProfileEdit.php(79): UApp->handleError()
#1 unknown(0): WUserProfileEdit->taskSave()
#2 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UWorklet.php(91): call_user_func_array()
#3 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UFormWorklet.php(129): WUserProfileEdit->__call()
#4 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UFormWorklet.php(129): WUserProfileEdit->save()
#5 unknown(0): WUserProfileEdit->taskProcess()
#6 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UWorklet.php(91): call_user_func_array()
#7 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UFormWorklet.php(76): WUserProfileEdit->__call()
#8 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UFormWorklet.php(76): WUserProfileEdit->process()
#9 unknown(0): WUserProfileEdit->taskBuild()
#10 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UWorklet.php(91): call_user_func_array()
#11 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UWidgetWorklet.php(58): WUserProfileEdit->__call()
#12 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UWidgetWorklet.php(58): WUserProfileEdit->build()
#13 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UWorkletManager.php(128): WUserProfileEdit->init()
#14 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UWorkletManager.php(99): UWorkletManager->add()
#15 /home/isuntv/文档/CodeC2I/protected/modules/base/worklets/WBaseInit.php(68): UWorkletManager->addCurrent()
#16 unknown(0): WBaseInit->taskWorklet()
#17 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UWorklet.php(91): call_user_func_array()
#18 /home/isuntv/文档/CodeC2I/protected/modules/base/worklets/WBaseInit.php(27): WBaseInit->__call()
#19 /home/isuntv/文档/CodeC2I/protected/modules/base/worklets/WBaseInit.php(27): WBaseInit->worklet()
#20 unknown(0): WBaseInit->taskBuild()
#21 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/worklets/UWorklet.php(91): call_user_func_array()
#22 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/yii/web/actions/UAction.php(30): WBaseInit->__call()
#23 /home/isuntv/文档/CodeC2I/framework/codec2i/framework/yii/web/actions/UAction.php(30): WBaseInit->build()
#24 /home/isuntv/文档/CodeC2I/framework/yii/framework/web/actions/CAction.php(76): UAction->run()
#25 /home/isuntv/文档/CodeC2I/framework/yii/framework/web/CController.php(318): UAction->runWithParams()
#26 /home/isuntv/文档/CodeC2I/framework/yii/framework/web/filters/CFilterChain.php(134): ProfileController->runAction()
#27 /home/isuntv/文档/CodeC2I/framework/yii/framework/web/filters/CFilter.php(41): CFilterChain->run()
#28 /home/isuntv/文档/CodeC2I/framework/yii/framework/web/filters/CFilterChain.php(131): UAccessFilter->filter()
#29 /home/isuntv/文档/CodeC2I/framework/yii/framework/web/CController.php(301): CFilterChain->run()
#30 /home/isuntv/文档/CodeC2I/framework/yii/framework/web/CController.php(275): ProfileController->runActionWithFilters()
#31 /home/isuntv/文档/CodeC2I/framework/yii/framework/web/CWebApplication.php(283): ProfileController->run()
#32 /home/isuntv/文档/CodeC2I/framework/yii/framework/web/CWebApplication.php(142): UApp->runController()
#33 /home/isuntv/文档/CodeC2I/framework/yii/framework/base/CApplication.php(162): UApp->processRequest()
#34 /home/isuntv/文档/CodeC2I/index.php(13): UApp->run()
</pre>

**Comment by lukechang0815** [comment]
已修復
